export const url = "http://localhost"
export const port = 8081

export const headers = [
    {label: "id", key: "id"},
    {label: "reportId", key: "reportId"},
    {label: "name", key: "name"},
    {label: "number of requests", key: "numberOfRequests.total"},
    {label: "number of successful requests", key: "numberOfRequests.ok"},
    {label: "number of failed requests", key: "numberOfRequests.ko"},
    {label: "min Response time total", key: "minResponseTime.total"},
    {label: "min Response time ok", key: "minResponseTime.ok"},
    {label: "min Response time ko", key: "minResponseTime.ko"},
    {label: "max Response time total", key: "maxResponseTime.total"},
    {label: "max Response time ok", key: "maxResponseTime.ok"},
    {label: "max Response time ko", key: "maxResponseTime.ko"},
    {label: "mean Response time total", key: "meanResponseTime.total"},
    {label: "mean Response time ok", key: "meanResponseTime.ok"},
    {label: "mean Response time ko", key: "meanResponseTime.ko"},
    {label: "standard deviation total", key: "standardDeviation.total"},
    {label: "standard deviation ok", key: "standardDeviation.ok"},
    {label: "standard deviation ko", key: "standardDeviation.ko"},
    {label: "percentiles1 total", key: "percentiles1.total"},
    {label: "percentiles 1 ok", key: "percentiles1.ok"},
    {label: "percentiles 1 ko", key: "percentiles1.ko"},
    {label: "percentiles2 total", key: "percentiles2.total"},
    {label: "percentiles 2 ok", key: "percentiles2.ok"},
    {label: "percentiles 2 ko", key: "percentiles2.ko"},
    {label: "percentiles3 total", key: "percentiles3.total"},
    {label: "percentiles 3 ok", key: "percentiles3.ok"},
    {label: "percentiles 3 ko", key: "percentiles3.ko"},
    {label: "percentiles4 total", key: "percentiles4.total"},
    {label: "percentiles 4 ok", key: "percentiles4.ok"},
    {label: "percentiles 4 ko", key: "percentiles4.ko"},
    {label: "group1 name", key: "group1.name"},
    {label: "group1 count", key: "group1.count"},
    {label: "group1 percentage", key: "group1.percentage"},
    {label: "group2 name", key: "group2.name"},
    {label: "group2 count", key: "group2.count"},
    {label: "group2 percentage", key: "group2.percentage"},
    {label: "group3 name", key: "group3.name"},
    {label: "group3 count", key: "group3.count"},
    {label: "group3 percentage", key: "group3.percentage"},
    {label: "group4 name", key: "group4.name"},
    {label: "group4 count", key: "group4.count"},
    {label: "group4 percentage", key: "group4.percentage"},
    {label: "meanNumberOfRequestsPerSecond total", key: "meanNumberOfRequestsPerSecond.total"},
    {label: "meanNumberOfRequestsPerSecond ok", key: "meanNumberOfRequestsPerSecond.ok"},
    {label: "meanNumberOfRequestsPerSecond ko", key: "meanNumberOfRequestsPerSecond.ko"},
];